package application;

public enum Block{MONETA,VELOCITA,SCUDO,LENTEZZA,VITA,VUOTO,TERRA,PERSONAGGIO,NEMICO,MURO,ERBA,SPECIALE,TUBO,BARILE,FINE,PORTALE,PONTE,MORTE,TELETRASPORTO,USATO,MINIZOMBIE,CREEPER}